In [53]:
import numpy as np
#linal
import sys
import matplotlib.pyplot as plt

In [54]:
def naiveGaussElimination(A):
    
    A = A.astype(float)
    n = len(A)
    x = np.zeros(n)
    
    for i in range(n):
        if A[i][i] == 0.0:
            sys.exit('Divide by zero detected!')
        
        print(f"Iterations {i +1} - Before elimination")
        print(A)
        
        for j in range(i+1, n):
            factor = A[j][i]/A[i][i]
            for k in range(i, n+1):
                A[j][k] = A[j][k] - factor * A[i][k]
    
    #Back Substitution
    x[n-1] = A[n-1][n]/A[n-1][n-1]
    for i in range(n-2, -1, -1):
        x[i] = A[i][n]
        for j in range(i+1, n):
            x[i] = x[i] - A[i][j] * x[j]
        x[i] = x[i]/A[i][i]
    
    print(x[0], x[1], x[2])
           
    return A

In [56]:

A = np.array([[10, 2, -1, 27],
                [-3, -6, 2, -61.5],
                [1, 1, 5, -21.5]])

print(naiveGaussElimination(A))

Iterations 1 - Before elimination
[[ 10.    2.   -1.   27. ]
 [ -3.   -6.    2.  -61.5]
 [  1.    1.    5.  -21.5]]
Iterations 2 - Before elimination
[[ 10.    2.   -1.   27. ]
 [  0.   -5.4   1.7 -53.4]
 [  0.    0.8   5.1 -24.2]]
Iterations 3 - Before elimination
[[ 10.           2.          -1.          27.        ]
 [  0.          -5.4          1.7        -53.4       ]
 [  0.           0.           5.35185185 -32.11111111]]
0.5 8.0 -6.0
[[ 10.           2.          -1.          27.        ]
 [  0.          -5.4          1.7        -53.4       ]
 [  0.           0.           5.35185185 -32.11111111]]
